apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-system
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      # 1.20
      image: docker.io/library/nginx@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d
      args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /etc/nginx/conf/nginx.conf
      ports:
        - name: https
          containerPort: 443
          hostPort: 443
        - name: http
          containerPort: 80
          hostPort: 80
      volumeMounts:
        - mountPath: /certs
          name: nginx-certs
          readOnly: true
        - mountPath: /etc/nginx/conf
          name: nginx-config
          #subPath: nginx.conf
          #readOnly: true
  volumes:
    - configMap:
        defaultMode: 420
        name: nginx-certs
      name: nginx-certs
    - configMap:
        defaultMode: 420
        name: nginx-config
      name: nginx-config