apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillian-mysql
  namespace: trillian-system
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trillian
    helm.sh/chart: trillian-0.1.16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trillian-mysql
  template:
    metadata:
      labels:
        app: trillian-mysql
        app.kubernetes.io/component: mysql
        app.kubernetes.io/instance: scaffold
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: trillian
        helm.sh/chart: trillian-0.1.16
    spec:
      containers:
        - name: trillian-mysql
          image: {{ trillian_db_image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          args:
            - --ignore-db-dir=lost+found
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: trillian-mysql
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-user
                  name: trillian-mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: trillian-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: mysql-database
                  name: trillian-mysql
          resources: {}
          livenessProbe:
            exec:
              command:
                - /etc/init.d/mysql
                - status
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - /etc/init.d/mysql
                - status
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: storage
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: minikube
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: trillian-mysql
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: trillian-mysql
