apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trillian
    helm.sh/chart: trillian-0.1.16
  name: trillian-mysql
  namespace: trillian-system
spec:
  containers:
    - args:
        - --ignore-db-dir=lost+found
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: trillian-mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: mysql-user
              name: trillian-mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: trillian-mysql
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: mysql-database
              name: trillian-mysql
      image: {{ trillian_db_image }}
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - /etc/init.d/mysql
            - status
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: trillian-mysql
      ports:
        - containerPort: 3306
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - /etc/init.d/mysql
            - status
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: storage
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: trillian-mysql
  serviceAccountName: trillian-mysql
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: trillian-mysql
