---
# defaults file for sigstore_scaffolding
system_packages:
    - podman
    - podman-plugins
    - firewalld

sigstore_podman_network: sigstore

cockpit_enabled: true

cockpit:
  enabled: true
  cockpit_packages:
    - cockpit-storaged
    - cockpit-podman
    - cockpit
  cockpit_manage_firewall: yes

skip_os_install: false

sigstore_rekor_templates:
  - manifests/rekor/redis-server.yaml
  - manifests/rekor/rekor-server.yaml

sigstore_trillian_templates:
  - manifests/trillian/trillian-mysql.yaml
  - manifests/trillian/trillian-logserver.yaml
  - manifests/trillian/trillian-logsigner.yaml

ctlog_enabled: true
tuf_enabled: true

trillian_enabled: true
trillian:
  mysql:
   user: mysql
   rootPassword: rootpassword
   password: password
   database: trillian
   host: trillian-mysql-pod
   port: 3306

config_dir: /etc/sigstore
certs_dir: "{{ config_dir }}/certs"
kube_manifest_dir: "{{ config_dir }}/manifests"
kube_configmap_dir: "{{ config_dir }}/configs"


local_certs_dir: /tmp/sigstore/certs

sigstore_private_key_filename: sigstore.key
sigstore_ca_filename: sigstore.pem
fulcio_private_key_filename: fulcio.key
fulcio_public_key_filename: fulcio.pub
fulcio_root_ca_filename: fulcio.pem
ctlog_private_key_filename: ctlog.key
ctlog_public_key_filename: ctlog.pub
rekor_signer_filename: rekor-signer.key
rekor_public_key_filename: rekor-pub-key.pub

local_sigstore_private_key: "{{ local_certs_dir }}/{{ sigstore_private_key_filename }}"
local_sigstore_ca: "{{ local_certs_dir }}/{{ sigstore_ca_filename }}"
local_fulcio_private_key: "{{ local_certs_dir }}/{{ fulcio_private_key_filename }}"
local_fulcio_public_key: "{{ local_certs_dir }}/{{ fulcio_public_key_filename }}"
local_fulcio_root_ca: "{{ local_certs_dir }}/{{ fulcio_root_ca_filename }}"
local_ctlog_private_key: "{{ local_certs_dir }}/{{ ctlog_private_key_filename }}"
local_ctlog_public_key: "{{ local_certs_dir }}/{{ ctlog_public_key_filename }}"
local_rekor_signer: "{{ local_certs_dir }}/{{ rekor_signer_filename }}"
local_rekor_public_key: "{{ local_certs_dir }}/{{ rekor_public_key_filename }}"
remote_sigstore_private_key: "{{ certs_dir }}/{{ sigstore_private_key_filename }}"
remote_sigstore_ca: "{{ certs_dir }}/{{ sigstore_ca_filename }}"
remote_fulcio_private_key: "{{ certs_dir }}/{{ fulcio_private_key_filename }}"
remote_fulcio_public_key: "{{ certs_dir }}/{{ fulcio_public_key_filename }}"
remote_fulcio_root_ca: "{{ certs_dir }}/{{ fulcio_root_ca_filename }}"
remote_ctlog_private_key: "{{ certs_dir }}/{{ ctlog_private_key_filename }}"
remote_ctlog_public_key: "{{ certs_dir }}/{{ ctlog_public_key_filename }}"
remote_rekor_signer: "{{ certs_dir }}/{{ rekor_signer_filename }}"
remote_rekor_public_key: "{{ certs_dir }}/{{ rekor_public_key_filename }}"

rekor_enabled: true
rekor_public_key_retries: 5
rekor_public_key_delay: 10
fulcio_server_config: "{{ kube_configmap_dir }}/fulcio-config.yaml"
fulcio_server_secret_config: "{{ kube_configmap_dir }}/fulcio-server-secret.yaml"
ctlog_secret_config: "{{ kube_configmap_dir }}/ctlog-secret.yaml"
tuf_secret_config: "{{ kube_configmap_dir }}/tuf-secret.yaml"
treeid_config: "{{ kube_configmap_dir }}/treeid-config.yaml"
rekor_sharding_config: "{{ kube_configmap_dir }}/rekor-sharding-config.yaml"
nginx_config: "{{ kube_configmap_dir }}/nginx-config.yaml"
nginx_certs_config: "{{ kube_configmap_dir }}/nginx-certs.yaml"
keycloak_certs_config: "{{ kube_configmap_dir }}/keycloak-certs.yaml"

setup_host_dns: true
base_hostname: ""

fulcio_enabled: true
fulcio_ca_passphrase: sigstore
ctlog_ca_passphrase: sigstore
rekor_ca_passphrase: sigstore
ct_logprefix: sigstoreansible

scaffolding_utils_image: quay.io/ablock/sigstore-scaffolding-helper:latest

keycloak_enabled: true
keycloak_url: keycloak.{{ base_hostname }}
keycloak_wait_increment_seconds: 60
keycloak_postgresql_user: "keycloak"
keycloak_postgresql_password: "keycloak"
keycloak_postgresql_database: "keycloak"
keycloak_admin_user: "admin"
keycloak_admin_password: "keycloaksigstore1234@"
keycloak_auth_realm: master
keycloak_realm: sigstore
keycloak_client: sigstore
keycloak_auth_endpoint: ""

keycloak_sigstore_client: sigstore
keycloak_sigstore_client_redirect_uris: "*"

keycloak_sigstore_users:
 - username: jdoe
   first_name: John
   last_name: Doe
   email: jdoe@redhat.com
   password: mysecurepassword

# Sigstore Images
fulcio_server_image: quay.io/securesign/fulcio:v1.3.1
trillian_log_server_image: quay.io/securesign/trillian_log_server:v1.2.2
trillian_logsigner_image: quay.io/securesign/trillian_log_signer:v1.2.2
rekor_image: quay.io/securesign/rekor-server:v1.2.2
ct_server_image: quay.io/securesign/ct_server:v0.6.4


# Supplement images
redis_image: registry.redhat.io/rhel9/redis-6@sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94
trillian_db_image: gcr.io/trillian-opensource-ci/db_server@sha256:22b7fddcb4bafc5692760d84dca5e86294363a94e8f0ecb8f5c39364d436e6d5
tuf_image: quay.io/securesign/tuf/server:latest
netcat_image: quay.io/securesign/netcat:v1.0.0
nginx_image: registry.access.redhat.com/ubi8/nginx-120@sha256:0d4543b4cf26eb46b1632006cc5b24a1925336973eb3ec17cdfb9fec372da5b8
curl_image: registry.access.redhat.com/ubi9/ubi-minimal:latest
