---
# defaults file for sigstore_scaffolding
system_packages:
    - podman
    - podman-plugins
    - firewalld

sigstore_podman_network: sigstore

cockpit_enabled: true

cockpit:
  enabled: true
  cockpit_packages:
    - cockpit-storaged
    - cockpit-podman
    - cockpit
  cockpit_manage_firewall: yes

skip_os_install: false

sigstore_rekor_templates:
  - manifests/rekor/redis-server.yaml
  - manifests/rekor/rekor-server.yaml

sigstore_trillian_templates:
  - manifests/trillian/trillian-mysql.yaml
  - manifests/trillian/trillian-logserver.yaml
  - manifests/trillian/trillian-logsigner.yaml

trillian:
  mysql:
   user: mysql
   rootPassword: rootpassword
   password: password
   database: trillian
   host: trillian-mysql
   port: 3306

config_dir: /etc/sigstore
certs_dir: "{{ config_dir }}/certs"
kube_manifest_dir: "{{ config_dir }}/manifests"
kube_configmap_dir: "{{ config_dir }}/configs"


local_certs_dir: /tmp/sigstore/certs

sigstore_private_key_filename: sigstore.key
sigstore_ca_filename: sigstore.pem
fulcio_private_key_filename: fulcio.key
fulcio_public_key_filename: fulcio.pub
fulcio_root_ca_filename: fulcio.pem
ctlog_private_key_filename: ctlog.key
ctlog_public_key_filename: ctlog.pub
rekor_signer_filename: rekor-signer.key
rekor_public_key_filename: rekor-pub-key.pub

local_sigstore_private_key: "{{ local_certs_dir }}/{{ sigstore_private_key_filename }}"
local_sigstore_ca: "{{ local_certs_dir }}/{{ sigstore_ca_filename }}"
local_fulcio_private_key: "{{ local_certs_dir }}/{{ fulcio_private_key_filename }}"
local_fulcio_public_key: "{{ local_certs_dir }}/{{ fulcio_public_key_filename }}"
local_fulcio_root_ca: "{{ local_certs_dir }}/{{ fulcio_root_ca_filename }}"
local_ctlog_private_key: "{{ local_certs_dir }}/{{ ctlog_private_key_filename }}"
local_ctlog_public_key: "{{ local_certs_dir }}/{{ ctlog_public_key_filename }}"
local_rekor_signer: "{{ local_certs_dir }}/{{ rekor_signer_filename }}"
local_rekor_public_key: "{{ local_certs_dir }}/{{ rekor_public_key_filename }}"
remote_sigstore_private_key: "{{ certs_dir }}/{{ sigstore_private_key_filename }}"
remote_sigstore_ca: "{{ certs_dir }}/{{ sigstore_ca_filename }}"
remote_fulcio_private_key: "{{ certs_dir }}/{{ fulcio_private_key_filename }}"
remote_fulcio_public_key: "{{ certs_dir }}/{{ fulcio_public_key_filename }}"
remote_fulcio_root_ca: "{{ certs_dir }}/{{ fulcio_root_ca_filename }}"
remote_ctlog_private_key: "{{ certs_dir }}/{{ ctlog_private_key_filename }}"
remote_ctlog_public_key: "{{ certs_dir }}/{{ ctlog_public_key_filename }}"
remote_rekor_signer: "{{ certs_dir }}/{{ rekor_signer_filename }}"
remote_rekor_public_key: "{{ certs_dir }}/{{ rekor_public_key_filename }}"


rekor_public_key_retries: 5
rekor_public_key_delay: 10
fulcio_server_config: "{{ kube_configmap_dir }}/fulcio-config.yaml"
fulcio_server_secret_config: "{{ kube_configmap_dir }}/fulcio-server-secret.yaml"
ctlog_secret_config: "{{ kube_configmap_dir }}/ctlog-secret.yaml"
tuf_secret_config: "{{ kube_configmap_dir }}/tuf-secret.yaml"
treeid_config: "{{ kube_configmap_dir }}/treeid-config.yaml"
rekor_sharding_config: "{{ kube_configmap_dir }}/rekor-sharding-config.yaml"
nginx_config: "{{ kube_configmap_dir }}/nginx-config.yaml"
nginx_certs_config: "{{ kube_configmap_dir }}/nginx-certs.yaml"
keycloak_certs_config: "{{ kube_configmap_dir }}/keycloak-certs.yaml"

setup_host_dns: true
base_hostname: ""

fulcio_ca_passphrase: sigstore
ctlog_ca_passphrase: sigstore
rekor_ca_passphrase: sigstore
ct_logprefix: sigstoreansible

scaffolding_utils_image: quay.io/ablock/sigstore-scaffolding-helper:latest

keycloak_wait_increment_seconds: 60
keycloak_postgresql_user: "keycloak"
keycloak_postgresql_password: "keycloak"
keycloak_postgresql_database: "keycloak"
keycloak_admin_user: "admin"
keycloak_admin_password: "keycloaksigstore1234@"
keycloak_auth_realm: master
keycloak_realm: sigstore
keycloak_client: sigstore
keycloak_auth_endpoint: ""

keycloak_sigstore_client: sigstore
keycloak_sigstore_client_redirect_uris: "*"

keycloak_sigstore_users:
 - username: jdoe
   first_name: John
   last_name: Doe
   email: jdoe@redhat.com
   password: mysecurepassword

# Images
fulcio_server_image: quay.io/rcook/fulcio:latest
redis_image: docker.io/redis@sha256:6c42cce2871e8dc5fb3e843ed5c4e7939d312faf5e53ff0ff4ca955a7e0b2b39
rekor_image: gcr.io/projectsigstore/rekor-server:v1.2.2
trillian_logsigner_image: gcr.io/projectsigstore/trillian_log_signer@sha256:b56ed0b7b5e9813c91b208ba6041c9342f9a53162d96943374e59b5289090f1f
ct_server_image: ghcr.io/sigstore/scaffolding/ct_server@sha256:7c791d3b7c15e817807f07d4cdb00406529a114702ad448ee857e1d0fc5fb5a9
trillian_log_server_image: gcr.io/projectsigstore/trillian_log_server@sha256:75dbbfc4c0b64334b985c4971fe58c30b9dd73d7aa54b15cee61223ff92aebf3
trillian_db_image: gcr.io/trillian-opensource-ci/db_server@sha256:22b7fddcb4bafc5692760d84dca5e86294363a94e8f0ecb8f5c39364d436e6d5
tuf_image: quay.io/ablock/tuf-server@sha256:c4f534807b331e97b107d908b7e0cf14a896399bc372bca6a2c7e4f6d730807c
netcat_image: docker.io/toolbelt/netcat@sha256:7d921b6d368fb1736cb0832c6f57e426c161593c075847af3378eb3185801cea
nginx_image: docker.io/library/nginx@sha256:38f8c1d9613f3f42e7969c3b1dd5c3277e635d4576713e6453c6193e66270a6d
curl_image: docker.io/curlimages/curl@sha256:dca6e1b1c8e7b8b8e7be4e79fc78a858d12fd56245cb31bfa281dbf7c73a6498