---
# defaults file for sigstore_scaffolding
system_packages:
    - podman
    - podman-plugins
    - firewalld

sigstore_podman_network: sigstore

cockpit:
  enabled: true
  cockpit_packages:
    - cockpit-storaged
    - cockpit-podman
    - cockpit
  cockpit_manage_firewall: yes

skip_os_install: false

sigstore_rekor_templates:
  - manifests/rekor/redis-server.yaml
  - manifests/rekor/rekor-server.yaml

cockpit_enabled: true
ctlog_enabled: true
tuf_enabled: true
trillian_enabled: true

trillian:
  mysql:
   user: mysql
   rootPassword: rootpassword
   password: password
   database: trillian
   host: trillian-mysql-pod
   port: 3306

config_dir: /etc/sigstore
certs_dir: "{{ config_dir }}/certs"
kube_manifest_dir: "{{ config_dir }}/manifests"
kube_configmap_dir: "{{ config_dir }}/configs"


local_certs_dir: /tmp/sigstore/certs

sigstore_private_key_filename: sigstore.key
sigstore_ca_filename: sigstore.pem
fulcio_private_key_filename: fulcio.key
fulcio_public_key_filename: fulcio.pub
fulcio_root_ca_filename: fulcio.pem
ctlog_private_key_filename: ctlog.key
ctlog_public_key_filename: ctlog.pub
rekor_signer_filename: rekor-signer.key
rekor_public_key_filename: rekor-pub-key.pub

local_sigstore_private_key: "{{ local_certs_dir }}/{{ sigstore_private_key_filename }}"
local_sigstore_ca: "{{ local_certs_dir }}/{{ sigstore_ca_filename }}"
local_fulcio_private_key: "{{ local_certs_dir }}/{{ fulcio_private_key_filename }}"
local_fulcio_public_key: "{{ local_certs_dir }}/{{ fulcio_public_key_filename }}"
local_fulcio_root_ca: "{{ local_certs_dir }}/{{ fulcio_root_ca_filename }}"
local_ctlog_private_key: "{{ local_certs_dir }}/{{ ctlog_private_key_filename }}"
local_ctlog_public_key: "{{ local_certs_dir }}/{{ ctlog_public_key_filename }}"
local_rekor_signer: "{{ local_certs_dir }}/{{ rekor_signer_filename }}"
local_rekor_public_key: "{{ local_certs_dir }}/{{ rekor_public_key_filename }}"
remote_sigstore_private_key: "{{ certs_dir }}/{{ sigstore_private_key_filename }}"
remote_sigstore_ca: "{{ certs_dir }}/{{ sigstore_ca_filename }}"
remote_fulcio_private_key: "{{ certs_dir }}/{{ fulcio_private_key_filename }}"
remote_fulcio_public_key: "{{ certs_dir }}/{{ fulcio_public_key_filename }}"
remote_fulcio_root_ca: "{{ certs_dir }}/{{ fulcio_root_ca_filename }}"
remote_ctlog_private_key: "{{ certs_dir }}/{{ ctlog_private_key_filename }}"
remote_ctlog_public_key: "{{ certs_dir }}/{{ ctlog_public_key_filename }}"
remote_rekor_signer: "{{ certs_dir }}/{{ rekor_signer_filename }}"
remote_rekor_public_key: "{{ certs_dir }}/{{ rekor_public_key_filename }}"

rekor_enabled: true
rekor_public_key_retries: 5
rekor_public_key_delay: 10
fulcio_server_config: "{{ kube_configmap_dir }}/fulcio-config.yaml"
fulcio_server_secret_config: "{{ kube_configmap_dir }}/fulcio-server-secret.yaml"
ctlog_secret: "{{ kube_configmap_dir }}/ctlog-secret.yaml"
ctlog_configmap_config: "{{ kube_configmap_dir }}/ctlog-config.yaml"
tuf_secret_config: "{{ kube_configmap_dir }}/tuf-secret.yaml"
treeid_config: "{{ kube_configmap_dir }}/treeid-config.yaml"
rekor_sharding_config: "{{ kube_configmap_dir }}/rekor-sharding-config.yaml"
nginx_config: "{{ kube_configmap_dir }}/nginx-config.yaml"
nginx_certs_config: "{{ kube_configmap_dir }}/nginx-certs.yaml"
systemd_directory: /etc/systemd/system

setup_host_dns: true
base_hostname: ""

fulcio_enabled: true
fulcio_ca_passphrase: sigstore
ctlog_ca_passphrase: sigstore
rekor_ca_passphrase: sigstore
ct_logprefix: sigstoreansible

scaffolding_utils_image: quay.io/ablock/sigstore-scaffolding-helper:latest

oidc_issuers: https://keycloak-keycloak-system.apps.platform-sts.pcbk.p1.openshiftapps.com/auth/realms/sigstore
sigstore_client_id: sigstore
issuer_url: https://keycloak-keycloak-system.apps.platform-sts.pcbk.p1.openshiftapps.com/auth/realms/sigstore
oidc_issuers_type: email

# Sigstore Images
fulcio_server_image: registry.redhat.io/rhtas-tech-preview/fulcio-rhel9@sha256:0421d44d2da8dd87f05118293787d95686e72c65c0f56dfb9461a61e259b8edc
trillian_log_server_image: registry.redhat.io/rhtas-tech-preview/trillian-logserver-rhel9@sha256:43bfc6b7b8ed902592f19b830103d9030b59862f959c97c376cededba2ac3a03
trillian_logsigner_image: registry.redhat.io/rhtas-tech-preview/trillian-logsigner-rhel9@sha256:fa2717c1d54400ca74cc3e9038bdf332fa834c0f5bc3215139c2d0e3579fc292
rekor_image: registry.redhat.io/rhtas-tech-preview/rekor-server-rhel9@sha256:8ee7d5dd2fa1c955d64ab83d716d482a3feda8e029b861241b5b5dfc6f1b258e
ct_server_image: registry.redhat.io/rhtas-tech-preview/ct-server-rhel9@sha256:6124a531097c91bf8c872393a6f313c035ca03eca316becd3c350930d978929f


# Supplement images
redis_image: registry.redhat.io/rhel9/redis-6@sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94
trillian_db_image: registry.redhat.io/rhtas-tech-preview/trillian-database-rhel9@sha256:fe4758ff57a9a6943a4655b21af63fb579384dc51838af85d0089c04290b4957
tuf_image: quay.io/securesign/tuf/server:latest
netcat_image: registry.redhat.io/rhtas-tech-preview/trillian-netcat-rhel9@sha256:b9fa895af8967cceb7a05ed7c9f2b80df047682ed11c87249ca2edba86492f6e
nginx_image: registry.access.redhat.com/ubi8/nginx-120@sha256:0d4543b4cf26eb46b1632006cc5b24a1925336973eb3ec17cdfb9fec372da5b8
curl_image: registry.access.redhat.com/ubi9/ubi-minimal:latest
