---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fulcio-config
  namespace: fulcio-system
data:
  config.json: |-
    {
      "OIDCIssuers": {
        "https://accounts.google.com": {
          "IssuerURL": "https://accounts.google.com",
          "ClientID": "sigstore",
          "Type": "email"
        },
        "https://oauth2.sigstore.dev/auth": {
          "IssuerURL": "https://oauth2.sigstore.dev/auth",
          "ClientID": "sigstore",
          "Type": "email",
          "IssuerClaim": "$.federated_claims.connector_id"
        },
        "https://token.actions.githubusercontent.com": {
          "IssuerURL": "https://token.actions.githubusercontent.com",
          "ClientID": "sigstore",
          "Type": "github-workflow"
        }
      }
    }