apiVersion: v1
kind: Pod
metadata:
  name: keycloak-postgresql
  namespace: keycloak-system
spec:
  containers:
    - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: keycloak-postgresql
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database
              name: keycloak-postgresql
      image: docker.io/library/postgres@sha256:2481115cad236897774fa13fef07ceb0e5fdc0a75457a047c441aada670cdfaf
      imagePullPolicy: IfNotPresent
      # livenessProbe:
      #   exec:
      #     command:
      #       - /etc/init.d/mysql
      #       - status
        # failureThreshold: 3
        # initialDelaySeconds: 30
        # periodSeconds: 10
        # successThreshold: 1
        # timeoutSeconds: 1
      name: keycloak-postgresql
      ports:
        - containerPort: 5432
          protocol: TCP
      # readinessProbe:
      #   exec:
      #     command:
      #       - /etc/init.d/mysql
      #       - status
        # failureThreshold: 3
        # initialDelaySeconds: 10
        # periodSeconds: 10
        # successThreshold: 1
        # timeoutSeconds: 1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: storage
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: keycloak-postgresql
  serviceAccountName: keycloak-postgresql
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: keycloak-postgresql
