apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "6963"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/name: ctlog
    pod-template-hash: d8b46868b
  name: ctlog
  namespace: ctlog-system
spec:
  containers:
    - args:
        - --http_endpoint=0.0.0.0:6962
        - --metrics_endpoint=0.0.0.0:6963
        - --log_config=/ctfe-keys/config
        - --alsologtostderr
      image: {{ ct_server_image }}
      imagePullPolicy: IfNotPresent
      name: ctlog
      ports:
        - containerPort: 6962
          protocol: TCP
        - containerPort: 6963
          protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /ctfe-keys
          name: keys
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
  serviceAccount: ctlog
  serviceAccountName: ctlog
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: keys
      # secret:
      configMap:
        defaultMode: 420
        name: ctlog-secret
        # secretName: ctlog-secret